name: JSON to CSV Conversion

on:
  push:

jobs:
  convert_json_to_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas

    - name: Convert JSON to CSV
      run: python json_to_csv.py

    - name: Commit and push changes
      run: |
         git config user.name "${{ github.actor }}"
         git config user.email "${{ github.actor }}@users.noreply.github.com"
         git add .
         git commit -m "Convert JSON to Table"
         git push
